sonar.projectKey=mrbitsdcf_mira-animator
sonar.projectName=mrbitsdcf/mira-animator
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/.git/**,**/dist/**,**/build/**,**/coverage/**,**/.devcontainer/**
sonar.lang.patterns.terraform=**/*.tf,**/*.tfvars
